@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User open help window;

if () then ([wants to copy URL])
    :copy URL of User Guide;
else ([else])
endif

:Close the help window;
stop
@enduml